### ISSUE TITLE
ports tree root: other locations

### ISSUE THREAD

**Issue by nunotexbsd** [HubTou/portstreelint#3]
Hello,

While `/usr/ports` is the standard location of ports, it is missing a config var or option that configs program to look at other locations.

As an example, ports-mgmt/portgrep:
```
General options:
  -R path     ports tree root (default: )
```

Also as a side note, for non portsnap users, an INDEX should be created or fetched so this program works:`
make index` or `make fetchindex`

**Comment by HubTou** [comment]
Hello Nuno,

You’re right! I’ll implement and document this later this week.

There’s an explanation of the false positives for your ports in the
discussion part of GitHub. I’ll also try to improve this soon.

Best regards,

Hubert

Le mer. 20 mars 2024 à 10:57, Nuno Teixeira ***@***.***> a
écrit :

**Comment by smyru** [comment]
Apart from a command line param, sensitivity to an ENV variable PORTSDIR (see: ports(7)) would be good.

**Comment by HubTou** [comment]
Indeed! Will do too!

**Comment by HubTou** [comment]
Hello,
Implemented your enhancements in [version 1.2.1](https://github.com/HubTou/portstreelint/releases/tag/1.2.1).
I'll now make the FreeBSD port update...

By the way, "make index" and "make fetchindex" commands were already documented under the [Files](https://github.com/HubTou/portstreelint#files) section of the documentation.

Feel free to send new ideas!

I'll now work on the configuration file.
